### ISSUE TITLE
Remove sid=xxx from all API calls (TherapyBox)

### ISSUE THREAD

**Issue by pdiveris** [jiscdev/la-app#12]
All sid=xxx references need to be removed from API calls - SID=xxx is only there for debugging when data is not available for the current student. Furthermore, not all logged users are allowed to pass the sid= param!

**Comment by TherapyBox** [comment]
I think we kept this out of builds and only used it to check outside of app, but I will check this

**Comment by michaelwebbjisc** [comment]
Ta, it's there for engagement graphs at the moment. I'm debugging by logging at the nginx logs to see what calls the app is making:

`87.113.194.140 - - [13/Jun/2016:14:59:09 +0000] "GET /graph/engagement?sid=202&scope=7d&module=LA101-1-2016S1-0 HTTP/1.1" 500 101 "-" "Dalvik/2.1.0 (Linux; U;$`
