### ISSUE TITLE
Can dismiss keyboard when adding notes to self logged activity

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/la-app#14]
Device: Nexus 6p

I can't work out how to dismiss the keyboard.  It seems to cover the 'log' button as well.

**Comment by TherapyBox** [comment]
Doesn't the android back button turn into a drop keyboard button in this instance?

**Comment by michaelwebbjisc** [comment]
Oh dear - I feel stupid now! I blame the fact I was testing iOS and Android at the same time!
