### ISSUE TITLE
No API call yet to find student UID from email address

### ISSUE THREAD

**Issue by leebaylis** [jiscdev/la-app#17]
Missing job story: As a student when trying to add friends in the student app I need to search for a friend by email address. 

Detail: Student passes email address to app, app passes email address to API, API returns Student identifier to app.

**Comment by TherapyBox** [comment]
We are able to do this from our side.

**Comment by robwynj** [comment]
Can I close this issue now?

Rob

**Comment by mparker-tbox** [comment]
yes, this is fine to close
