### ISSUE TITLE
Name and email address changed in data but not updated in App

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/la-app#2]
See duns for an example.

Affects iOS and Android.

**Comment by TherapyBox** [comment]
Duns changed. Craig seems the same, has he also been changed?

**Comment by michaelwebbjisc** [comment]
Thanks - test in Android and iOS.  I've changed Craig's name from Donna to Craig and it worked fine, as well as updating Duns Hunt to Duns Hunter
