### ISSUE TITLE
Entering note when Logging an Activity causes keyboard UI issues

### ISSUE THREAD

**Issue by leebaylis** [jiscdev/la-app#21]
Keyboard appears at bottom of screen but it is not intuitive how to get it to go away, and it eclipses the  Save button.

**Comment by leebaylis** [comment]
Clarification: this is android 4.2.2 so there is no 'keyboard go away' button and the 'Done' button is not appearing on the keyboard -- it stays as carriage return

**Comment by leebaylis** [comment]
Michael notes this is a clarification/continuation of issue 14

**Comment by TherapyBox** [comment]
moved the save button so it appears above the keybaord when typing
