### ISSUE TITLE
Non-obvious wording when logging new activity

### ISSUE THREAD

**Issue by leebaylis** [jiscdev/la-app#24]
to me, 'report activity' and 'log activity' mean the same thing. Perhaps we should say 'use the app to time myself on an activity' and 'report activity I carried out offline' or something a bit clearer

**Comment by TherapyBox** [comment]
I've had that issue too. How about "Start Activity Now (Timed)" and "Report Completed Activity"?

**Comment by leebaylis** [comment]
OK, sounds good!

**Comment by TherapyBox** [comment]
Need Welsh translation for these, but I think missing welsh is listed as a separate item here :)
