### ISSUE TITLE
App Crash on Login, followed by Crash - random behaviour - (Android 6.0.1, Galaxy S6)

### ISSUE THREAD

**Issue by robwynj** [jiscdev/la-app#35]
Device: Galaxy S6 (SM-G920F)
Opsys: Android 6.0.1 (Kernel: 3.10.61-7025264)

Crashed first time after attempting to log-in via "Duns" account on "Test" Shib.

Second attempt - crashed upon selecting of "Test".

Tried again - logged me in automatically, works fine!?

Previous Android App (Installed Feb 2016) was also uninstalled properly.

**Comment by TherapyBox** [comment]
I think this is resolved but will send a new build so you can check (it's not crashing on the android 6 phone we have in the office here, but we don't have the exact same model as yours)

**Comment by robwynj** [comment]
Mark for re-test via RWJ.

Kind Regards,

Rob
