### ISSUE TITLE
Missing "Report Feature/ Bug" option (email out) in Settings (iOS)

### ISSUE THREAD

**Issue by robwynj** [jiscdev/la-app#36]
Agreed option (to support evaluation projects with institutions) with Therapy Box.

Agreed that it would be in both iOS & Android - but is missing in iOS.

Mail linkage works in Android - prescribed text to be provided via RWJ/ Niall Sclater in due course (for auto population into email body).

**Comment by TherapyBox** [comment]
This is done, but could do with wording if this needs to be changed (also in welsh)

**Comment by robwynj** [comment]
Happy to provide welsh text for this - will need some newlines between the prompts for information, and an opening sentence to ask the user to submit the information against those prompts....
