### ISSUE TITLE
Can't login after registering new user

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/la-app#4]
I've registered a new user and can't login.

The user registered is Ewart

Android hangs and iOS crashes

**Comment by robwynj** [comment]
ACTION - @TB

**Comment by TherapyBox** [comment]
We're using the student/modules command in login -- when we run for duns we get {
  "LA101-1-2016S1-0": [
    "BASIC LA 1",
    "LA101",
    "202"
  ],
  "LA102-1-2016S1-0": [
    "BASIC LA 2",
    "LA102",
    "202"
  ]
}

When we run for Ewart it's sending back empty brackets. Currently, i think this is the only call that brings back a student number, which is why we're using it.

**Comment by michaelwebbjisc** [comment]
OK, empty brackets is a valid response.

I've added STUDENT_ID to 

https://sp.data.alpha.jisc.ac.uk/student

so now you should get back:

```
{  
   "FIRST_NAME":"Ewart",
   "LAST_NAME":"Hunt",
   "PRIMARY_EMAIL_ADDRESS":"ewart@mwebb.me.uk",
   "APPSHIB_ID":"https:\/\/test-idp.ukfederation.org.uk\/idp\/shibboleth!https:\/\/sp.data.alpha.jisc.ac.uk\/shibboleth!IVM6K+\/vFzfN4M2RgyB5t\/JVstc=",
   "STUDENT_ID":"90626240"
}
```

**Comment by TherapyBox** [comment]
Great. I think this should just be a change to the backend, so hopefully we can sort it out pretty quickly. Checking all other feedback now, but at a first glance it all seems pretty manageable

**Comment by TherapyBox** [comment]
Hi Michael, was Ewart already registered? Currently it's logging him straight in, was expecting to see the registration screen but wanted to check before going further into it.

**Comment by michaelwebbjisc** [comment]
Yes, he's registered, but not currently taking any modules.  So that sounds right.

**Comment by michaelwebbjisc** [comment]
Tested - Ewart behaving as expected now.
