### ISSUE TITLE
API: Basic activity account not working

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/la-app#6]
If you add new activity the value doesn't increase. If it's using the query in postman, then it's looking at the wrong value for actor:

Actor.name instead of actor.account.name

**Comment by robwynj** [comment]
Is this because we are not sourcing self-admitted activity data via our APIs? Just want clarity around how we "add new activity" - I assume you've done this via VLE, and not the App itself!

**Comment by michaelwebbjisc** [comment]
Sorry, should have been clearer, I mean via the VLE, ie doing something in moodle

**Comment by michaelwebbjisc** [comment]
Fixed by Petros and tested by Michael
