### ISSUE TITLE
iOS: Test says USE_PHOTO

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/la-app#7]
When taking photo

**Comment by robwynj** [comment]
Agreed - the folder structure when selecting photos also show's "_" folder names - should be actual folder names, as shown in iOS.

ACTION - TB to fix

**Comment by michaelwebbjisc** [comment]
OK, probably best to create a seperate issue for the second problem.

**Comment by robwynj** [comment]
#10

**Comment by TherapyBox** [comment]
This has been fixed
